.TH SIMKER 1 "January 2026" "1.0" "User Commands"
.SH NAME
Simker \- A Mixed-Signal simulation and developpement container
.SH DESCRIPTION
.B Simker
Provide an integrated environment for electronics simulations and developpement, with Mixed Signals abilities.
.PP
And, due to it's architecture within a docker container, this provide a stable environment, unlinked to your host OS, which enable stability and predictability.
Leonard HEYWANG <leonard.heywang@proton.me>